namespace: dev-presidio
bases:
- ../../../base
- ../../../redis/master
resources:
- common-configmaps.yaml
- redis-configmaps.yaml
- analyzer-configmaps.yaml
- anonymizer-configmaps.yaml
- anonymizer-image-configmaps.yaml
- api-configmaps.yaml
- ocr-configmaps.yaml
- recognizerstore-configmaps.yaml
- scheduler-configmaps.yaml
- ingress.yaml
patches: []
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: redis
  type: Opaque
  commands: {}
    # REDIS_PASSWORD: "aws --region us-east-1 secretsmanager get-secret-value --secret-id kubernetes/dev/presidio/secrets --query SecretString --output text | jq -j '.REDIS_PASSWORD'"
- name: analyzer
  type: Opaque
  commands: {}
- name: anonymizer
  type: Opaque
  commands: {}
- name: anonymizer-image
  type: Opaque
  commands: {}
- name: api
  type: Opaque
  commands: {}
- name: ocr
  type: Opaque
  commands: {}
- name: recognizerstore
  type: Opaque
  commands: {}
- name: scheduler
  type: Opaque
  commands: {}
- name: presidio-demo-presidio-api.anonymize.anonymize-fields
  type: Opaque
  commands:
    presidio-demo-presidio-api.anonymize.anonymize-fields: |
        echo '{"fieldTypeTransformations":[{"fields":[{"name":"CREDIT_CARD"}],"transformation":{"replaceValue":{"newValue":"\u003cRedacted\u003e"}}},{"fields":[{"name":"CRYPTO"}],"transformation":{"replaceValue":{"newValue":"\u003cRedacted\u003e"}}},{"fields":[{"name":"EMAIL_ADDRESS"}],"transformation":{"replaceValue":{"newValue":"\u003cRedacted\u003e"}}},{"fields":[{"name":"IBAN_CODE"}],"transformation":{"replaceValue":{"newValue":"\u003cRedacted\u003e"}}},{"fields":[{"name":"NRP"}],"transformation":{"replaceValue":{"newValue":"\u003cRedacted\u003e"}}},{"fields":[{"name":"IP_ADDRESS"}],"transformation":{"replaceValue":{"newValue":"\u003cRedacted\u003e"}}},{"fields":[{"name":"LOCATION"}],"transformation":{"replaceValue":{"newValue":"\u003cRedacted\u003e"}}},{"fields":[{"name":"PERSON"}],"transformation":{"replaceValue":{"newValue":"\u003cRedacted\u003e"}}},{"fields":[{"name":"PHONE_NUMBER"}],"transformation":{"replaceValue":{"newValue":"\u003cRedacted\u003e"}}},{"fields":[{"name":"US_BANK_NUMBER"}],"transformation":{"replaceValue":{"newValue":"\u003cRedacted\u003e"}}},{"fields":[{"name":"US_DRIVER_LICENSE"}],"transformation":{"replaceValue":{"newValue":"\u003cRedacted\u003e"}}},{"fields":[{"name":"US_ITIN"}],"transformation":{"replaceValue":{"newValue":"\u003cRedacted\u003e"}}},{"fields":[{"name":"US_VIN"}],"transformation":{"replaceValue":{"newValue":"\u003cRedacted\u003e"}}},{"fields":[{"name":"US_PASSPORT"}],"transformation":{"replaceValue":{"newValue":"\u003cRedacted\u003e"}}},{"fields":[{"name":"CAN_ROUTING"}],"transformation":{"replaceValue":{"newValue":"\u003cRedacted\u003e"}}},{"fields":[{"name":"CAN_TRANSIT"}],"transformation":{"replaceValue":{"newValue":"\u003cRedacted\u003e"}}},{"fields":[{"name":"US_SSN"}],"transformation":{"replaceValue":{"newValue":"\u003cRedacted\u003e"}}},{"fields":[{"name":"DOMAIN_NAME"}],"transformation":{"replaceValue":{"newValue":"\u003cRedacted\u003e"}}},{"fields":[{"name":"DATE_TIME"}],"transformation":{"replaceValue":{"newValue":"\u003cRedacted\u003e"}}},{"fields":[{"name":"CAN_POSTAL"}],"transformation":{"replaceValue":{"newValue":"\u003cRedacted\u003e"}}},{"fields":[{"name":"INDIAN_LAND_NUMBER"}],"transformation":{"replaceValue":{"newValue":"\u003cRedacted\u003e"}}},{"fields":[{"name":"INDIAN_PHONE_NUMBER"}],"transformation":{"replaceValue":{"newValue":"\u003cRedacted\u003e"}}},{"fields":[{"name":"UK_SORT_CODE"}],"transformation":{"replaceValue":{"newValue":"\u003cRedacted\u003e"}}}]}'
