apiVersion: v1
kind: Service
metadata:
  labels:
    app: analyzer
    service: analyzer
  name: analyzer
spec:
  ports:
  - name: grpc
    port: 3001
    protocol: TCP
    targetPort: grpc
  selector:
    app: analyzer
