apiVersion: v1
kind: Service
metadata:
  labels:
    app: anonymizer
    service: anonymizer
  name: anonymizer
spec:
  ports:
  - name: grpc
    port: 3001
    protocol: TCP
    targetPort: grpc
  selector:
    app: anonymizer
