apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ocr
  name: ocr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ocr
    spec:
      containers:
      - name: presidio
        image: mcr.microsoft.com/presidio-ocr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          protocol: TCP
          name: grpc
        envFrom:
        - configMapRef:
            name: ocr
        - configMapRef:
            name: common
        - secretRef:
            name: ocr
        env:
        - name: PRESIDIO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: GRPC_PORT
          value: "3001"
        resources: {}
      restartPolicy: Always
