apiVersion: v1
kind: Service
metadata:
  labels:
    app: ocr
    service: ocr
  name: ocr
spec:
  ports:
  - name: grpc
    port: 3001
    protocol: TCP
    targetPort: grpc
  selector:
    app: ocr
