---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: presidio
  name: scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scheduler
subjects:
- kind: ServiceAccount
  name: scheduler

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: presidio
  name: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api
subjects:
- kind: ServiceAccount
  name: api
