---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: presidio
  name: scheduler
rules:
- apiGroups:
  - ""
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - create
  - update
  - patch
  - delete
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: presidio
  name: api
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
  - patch
  - delete
