apiVersion: v1
kind: Service
metadata:
  labels:
    app: scheduler
    service: scheduler
  name: scheduler
spec:
  ports:
  - name: grpc
    port: 3001
    protocol: TCP
    targetPort: grpc
  selector:
    app: scheduler
