
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-master
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app: redis
    role: master
